coeventer/ccf

.octopolo.yml
Deploy Plan
-----------
Rollback Plan
-------------
URLs
----
QA Plan
-------
=> Use Octopolo to Add Octopolo yml

app/controllers/admin/projects_controller.rb, app/views/admin/projects/_form.html.erb
Deploy Plan
-----------
Rollback Plan
-------------
URLs
----
QA Plan
-------
=> Event Select on admin

app/views/events/_registration.html.erb
Adds a `:confirm` attribute for the `Unregister` button displayed on events. It's exactly equivalent to the admin Unregister confirmation.
=> Adds confirm for event unregistration

app/controllers/presentations_controller.rb
Signed-off-by: Max Fierke <max@maxfierke.com>
=> Allow project presentation title updates

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/invitations_controller.rb, app/decorators/invitation_decorator.rb, app/models/concerns/tokenable.rb, app/models/event.rb, app/models/invitation.rb, app/models/user.rb, app/views/invitations/index.html.erb, app/views/invitations/show.html.erb, app/views/shared/campuscodefest/_org_navigation.html.erb, config/routes.rb, db/migrate/20150825132119_create_invitations.rb, db/schema.rb, spec/factories/invitations.rb, spec/models/invitation_spec.rb
Adds backend for inviting users to organizations and events.
=> Invitations Backend

app/views/home/index.html.erb
Kind of a blitzkrieg over a snack break.
=> a few tweaks to the home page verbiage

README.md
Just ran through the installation process...added the bower task and tweaked a couple of things.
=> some readme tweaks after re-installing the app

app/controllers/sessions_controller.rb, app/models/provider_user.rb, app/models/user.rb, db/migrate/20151110030112_create_provider_users.rb, db/schema.rb, spec/factories/provider_users.rb, spec/models/provider_user_spec.rb
Deploy Plan
-----------
Rollback Plan
-------------
URLs
----
QA Plan
-------
=> Add Provider Users

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/helpers/application_helper.rb, app/models/provider_user.rb, app/models/user.rb, app/views/events/_registration.html.erb, app/views/layouts/application.html.erb, app/views/layouts/common/_sign_in.html.erb, app/views/layouts/organization.html.erb, app/views/organization_home/index.html.erb, app/views/project_comments/_comments.html.erb, app/views/sessions/new.html.erb, app/views/sessions/new.js.erb, app/views/shared/campuscodefest/_navigation.html.erb, app/views/shared/campuscodefest/_org_navigation.html.erb, config/config.yml.example, config/initializers/omniauth.rb
Deploy Plan
-----------
Rollback Plan
-------------
URLs
----
QA Plan
-------
=> Add Facebook Auth

app/controllers/organization_lib.rb, app/models/event.rb, app/views/admin/after_create/privacy.html.erb, app/views/admin/builder/ideas.html.erb, app/views/admin/builder/information.html.erb, app/views/admin/builder/registration.html.erb, app/views/shared/_organization_form.html.erb, db/migrate/20151124022206_add_time_zone_to_organization.rb, db/schema.rb
Add a time_zone field to organizations, make sure it's respected in admin forms. Should float through to views but double check there too.
Deploy Plan
-----------
Rollback Plan
-------------
URLs
----
QA Plan
-------
=> Add Organization TZ respect BOOM

.gitignore, .travis.yml, config/config.yml.example, config/database.yml.example, config/environments/test.rb, spec/mailers/registrations_mailer_spec.rb
Goal is to have all written tests pass, and to add a Travis-CI file to run CI on 2.x rubies
=> [WIP] Fix tests and make Travis-CI work

app/helpers/application_helper.rb, app/models/event.rb, spec/models/event_spec.rb
Adding the ability to format datetimes in SQLite
Addresses #82
=> Trying in_time_zone instead of directly calling it

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/views/layouts/common/_sign_in.html.erb, app/views/user_mailer/confirm_email.erb, app/views/users/set_email.html.erb, config/config.yml.example, config/initializers/omniauth.rb, config/routes.rb, db/migrate/20151213171916_add_email_confirmation_token_to_users.rb, db/migrate/20151217184014_confirm_email_of_all_users.rb, db/schema.rb, spec/controllers/sessions_spec.rb, spec/controllers/users_controller.rb, spec/models/user_spec.rb
Added Meetup oAuth provider, DRYed up oAuth path functions, Got rid of Ruby Syntax checker warnings in user model
TODO: Handle not getting a proper email address from Meetup
Addresses #74
=> Adding Login via Meetup

app/views/registration_mailer/registration_created.html.erb, app/views/registration_mailer/registration_created.text.erb, db/schema.rb, spec/controllers/sessions_spec.rb
=> Registration email

app/controllers/sessions_controller.rb, app/controllers/users_controller.rb
Deploy Plan
-----------
Rollback Plan
-------------
URLs
----
QA Plan
-------
=> Better Email Confirm Redirects

app/views/home/index.html.erb
small change. fixes alignment on the home page of the "What... Why?!?" header.
=> view: wrap header in bootstrap col div

app/views/registration_mailer/registration_created.html.erb, app/views/registration_mailer/registration_created.text.erb
Got a note from a user mentioning these typos.
=> fixes a few typos

app/controllers/event_registrations_controller.rb, app/models/event_registration.rb, app/views/admin/event_registrations/index.html.erb, app/views/event_registrations/_form.html.erb, app/views/event_registrations/new.html.erb, db/migrate/20160505205343_add_display_name.rb, db/schema.rb, spec/factories/event_registrations.rb, spec/models/event_registrations_spec.rb
Description and Impact
----------------------
Add display name to registration. For issue #108.
Deploy Plan
-----------
> Does Platform Operations need to know anything special about this deploy? Are migrations present?
Rollback Plan
-------------
* To roll back this change, revert the merge with: `git revert -m 1 MERGE_SHA` and perform another deploy.
URLs
----
> Links to bug tickets or user stories.
QA Plan
-------
> Fill in scenarios below. Review [QA Best Practices](https://source.sportngin.com/page/show/1227795-qa-best-practices).
=> #108 Reg Display Name

app/views/layouts/common/_sign_in.html.erb
Description and Impact
----------------------
Some improvements based on #96.
Deploy Plan
-----------
> Does Platform Operations need to know anything special about this deploy? Are migrations present?
Rollback Plan
-------------
* To roll back this change, revert the merge with: `git revert -m 1 MERGE_SHA` and perform another deploy.
URLs
----
> Links to bug tickets or user stories.
QA Plan
-------
> Fill in scenarios below. Review [QA Best Practices](https://source.sportngin.com/page/show/1227795-qa-best-practices).
=> Improve Sign in

app/mailers/comment_mailer.rb, app/views/comment_mailer/comment_posted.html.erb, app/views/comment_mailer/comment_posted.text.erb
adds comment author to email message
=> add comment author to email message

Gemfile.lock, app/controllers/organization_controller.rb, app/models/project.rb, app/views/home/index.html.erb, app/views/projects/_project_list.html.erb, db/migrate/20160513192448_add_hotness_to_project.rb, db/schema.rb, lib/tasks/hotness.rake
Adds hotness column and task to calculate for upcoming events.
=> Implement hotness

Gemfile, Gemfile.lock, app/helpers/application_helper.rb, app/views/layouts/common/_sign_in.html.erb, config/config.yml.example, config/initializers/omniauth.rb
Dave wants :octocat: login here #128
So why not implement it.
=> Implement github login

app/controllers/admin/builder_controller.rb, app/models/event.rb, app/models/event_customization.rb, app/views/admin/builder/_nav.html.erb, app/views/admin/builder/customizations.html.erb, app/views/events/show.html.erb, app/views/projects/_form.html.erb, app/views/projects/_pretty_form.html.erb, db/migrate/20170226114113_add_customizations.rb, db/schema.rb
- Adds ability to customize certain text for an event...
https://github.com/coeventer/ccf/issues/139
=> #139 Customizations

app/models/message.rb, app/views/contact/new.html.erb, app/views/contact_mailer/contact_admins.html.erb
https://github.com/coeventer/ccf/issues/142
=> Add event as option for contact form

app/views/projects/_form.html.erb, app/views/projects/_pretty_form.html.erb
https://github.com/coeventer/ccf/issues/134
=> Make it bigger

app/models/ability.rb, app/models/event.rb, app/views/events/_registration.html.erb, app/views/organization_home/index.html.erb
https://github.com/coeventer/ccf/issues/138
=> Allow unregistering when even full, clean up a bit

app/models/user.rb
https://github.com/coeventer/ccf/issues/135
=> Remove provider users when deactivating
